version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers-legacy
        environment:
          REDIS_HOST: redis
          REDIS_PORT: 6379
          DATABASE_URL: postgres://circle:circle@pg:5432/circle_test
      - image: circleci/redis:rc-alpine3.11
        name: redis
      - image: circleci/postgres:9.6-alpine
        name: pg
        environment:
          POSTGRES_PASSWORD: circle
          POSTGRES_USER: circle
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          name: install dep
      - run:
          command: |
            . venv/bin/activate
            pip install -r requirements/local.txt
          name: install other dep
      - run:
          command: |
            . venv/bin/activate
            env
      - run:
          name: Waiting for Redis to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z redis 6379 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Redis && exit 1
      - run:
          name: Waiting for PG to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z pg 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for PG && exit 1
      - run:
          command: | 
            . venv/bin/activate
            pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
